title: Erica Bertan
logo: /assets/img/jericho-cervantes-1437109-unsplash.jpg
description: Computer Science, Machine Learning
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
twitter_username: bertanerica
github_username: ericabertan
linkedin_username: erica-bertan-1303154b/
facebook_username: ericabertan1
medium_username: ericabertan
